# This is a basic workflow to help you get started with Actions

name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    run-on: ubuntu-latest
    steps:
      - name: ci_build
        run: echo "Hello_CI"
    
