# This is a basic workflow to help you get started with Actions

name: CI
on: workflow_dispatch:
jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - name: ci_build
        run: echo "Hello_CI"
    
